name: "Publish Godot Game to GitHub Pages (Windows)"

env:
  GODOT_VERSION: 4.3

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download and Extract Godot
        run: |
          Invoke-WebRequest -Uri "https://github.com/godotengine/godot-builds/releases/download/4.3-stable/Godot_v4.3-stable_win64.exe.zip" -OutFile godot.zip
          Expand-Archive -Path godot.zip -DestinationPath .
          Rename-Item -Path "Godot_v4.3-stable_win64.exe" -NewName "godot.exe"

      - name: Create Build Directory
        run: New-Item -ItemType Directory -Path build/web -Force

      - name: Build for Web
        run: |
          .\godot.exe --headless --export-release "Web" build/web/index.html project/project.godot
        shell: cmd

      - name: Add coi-service-worker
        run: |
          git clone https://github.com/gzuidhof/coi-serviceworker.git
          Move-Item coi-serviceworker\coi-serviceworker.js build\web\coi-serviceworker.js
          (Get-Content build\web\index.html) -replace '<head>', '<head><script src="coi-serviceworker.js"></script>' | Set-Content build\web\index.html
        shell: pwsh

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true
          user_name: "github-ci[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: "Publish Godot Web Game to GitHub Pages"